- name: Add MongoDB repository
  yum_repository:
    name: MongoDB
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc
    file: mongodb

- name: Install MongoDB
  yum:
    name: mongodb-org
    state: present

- name: Update MongoDB Listen Address
  notify:
    - Restart MongoDB
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

# Handlers will run at the ending of the play , it vll notify us if their is any change then only it will come into picture

- name: Start MOngoDB service
  systemd:
    name: mongod
    enabled: yes
    state: started

- name: Download Package
  include_role:
    name: commmon
    tasks_from: download-from-github
  vars:
    APP_DIR: /tmp/mongodb-main
    EXTRACT_DIR: /tmp

- name: Load Schema
  community.mongodb_shell:
    file: "/tmp/mongodb-main/{{items}}"
    idempotent: yes
  loop:
    - users.js
    - catalogue.js


