- name: Demo on conditions
  hosts: localhost
  vars:
    IS_RUN: false
    COUNT: 2
  tasks:
    ## Boolean condition
    - name: Run based on user input
      debug:
        msg: Hello World
      when: IS_RUN