- name: Clean Known Hosts entries
  hosts: localhost
  tasks:
    - name: Clear Known Hosts file
      file:
        path: ~/.ssh/known_hosts
        state: absent

- name: Setup Roboshop Project
  hosts: FRONTEND
  become: yes
  roles:
   - name: Load Frontend Role
     role: frontend

