- name: Install the Nginx
  yum:
    name: nginx
    state: present

- name: Download Package
  include_role:
    name: common
    tasks_from: download-from-github.yml
  vars:
    APP_DIR: /usr/share/nginx/html
    EXTRACT_DIR: /usr/share/nginx
    APP_TYPE: web


- name: Copy Extracted Directory
  ansible.builtin.copy:
    src: /usr/share/nginx/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Copy Nginx Roboshop config
  copy:
   src: roboshop.conf
   dest: /etc/nginx/default.d/roboshop.conf

- name: Update Nginx main confi file
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start Nignx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes
  ignore_errors: true

- name: Setup filebeat
  include_role:
    name: common
    tasks_from: filebeat
  vars:
   IS_STRUCTURED: false
   FILENAME: /var/log/nginx/access.log
   APPTYPE: NGINX

